14899 used reactjs and ui-kit for report
konturio/make-profiler pull request #29
Opened 2023-02-20 13:22 UTC by saricicekibrahim

2023-02-20 14:19 UTC, IlyaIzr commented on make_profiler/report/src/components/report.jsx
> +                if (a[sortField] === undefined || b[sortField] === undefined) return 0;
3rd field will never happen

2023-02-21 17:18 UTC, Komzpa commented on make_profiler/report/README.md
> +# Getting Started with Create React App
this is a stub and stubs should not be

2023-02-21 17:20 UTC, Komzpa requested changes

2023-02-21 17:20 UTC, Komzpa commented on make_profiler/report/public/index.html
> +      content="Web site created using create-react-app"
stub

2023-02-21 17:20 UTC, Komzpa commented on make_profiler/report/src/App.test.js
> +test('renders learn react link', () => {
stub

2023-03-14 11:11 UTC, closed without merging